import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const compat = new FlatCompat({ baseDirectory: __dirname });

const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      // k6 scripts run in k6's own runtime, not Node, and import from
      // https:// specifiers that ESLint cannot resolve.
      'loadtest/**',
      // Generated by Next on every build; its triple-slash references are not
      // ours to fix.
      'next-env.d.ts',
    ],
  },

  ...compat.extends('next/core-web-vitals', 'next/typescript', 'prettier'),

  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      // console.log is a debugging leftover; warn and error are intentional
      // operational output and are allowed.
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },

  {
    // Scripts and tests legitimately print to stdout and use loose typing.
    files: ['prisma/seed.ts', 'tests/**/*.ts', 'scripts/**/*.ts'],
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
];

export default config;
