import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypeScript from 'eslint-config-next/typescript';
import prettier from 'eslint-config-prettier/flat';

/**
 * ESLint flat config for every workspace.
 *
 * eslint-config-next 16 ships native flat configs, each exported as an array,
 * so they are spread in directly. The previous config wrapped the legacy names
 * in `FlatCompat`, which crashed under v16 with a circular-structure error while
 * validating the plugin objects — the compat layer is only for configs that are
 * still in eslintrc format, and these no longer are.
 *
 * Order matters: Prettier's config comes after the Next configs so it can turn
 * off the stylistic rules they enable. Our own rules come last so they win.
 */
const config = [
  {
    ignores: [
      '**/.next/**',
      '**/node_modules/**',
      '**/coverage/**',
      '**/dist/**',
      '**/playwright-report/**',
      '**/test-results/**',
      // k6 scripts run in k6's own runtime, not Node, and import from
      // https:// specifiers that ESLint cannot resolve.
      'loadtest/**',
      // Generated by Next on every build.
      '**/next-env.d.ts',
    ],
  },

  ...nextCoreWebVitals,
  ...nextTypeScript,
  prettier,

  {
    // The Next plugin looks for the app directory from here; it lives in the
    // frontend workspace.
    settings: { next: { rootDir: 'frontend/' } },
  },

  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      // console.log is a debugging leftover; warn and error are intentional
      // operational output and are allowed.
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },

  {
    // Scripts, seeds and tests legitimately print to stdout and use loose typing.
    files: ['backend/prisma/seed.ts', '**/tests/**/*.ts', '**/scripts/**/*.{ts,mjs}'],
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
];

export default config;
